### ISSUE TITLE
Trying to Install homebridge-honeywell-home via NPM

### ISSUE THREAD

**Issue by erfind** [d0n4v4nb3ck3r/honeywellhome-api#1]
Hey! I'm trying to install homebridge-honeywell-home but it fails.  I believe it directs somehow back to your GitHub but fails to install.  The webpage I found that linked here was https://www.npmjs.com/package/homebridge-honeywell-home Is there as way to get this to work instead of getting an error.

**Comment by d0n4v4nb3ck3r** [comment]
Not sure. Not the one that wrote the code. If you want to fix it you can
